package com.gumihoy.sql.basic.parser;

/**
 * https://ronsavage.github.io/SQL/sql-2003-2.bnf.html
 *
 * @author kent on 2019-06-13.
 */
public class SQLToken {

    public final TokenKind kind;
    public final int line;
    public final int col;

    public SQLToken(TokenKind kind, int line, int col) {
        this.kind = kind;
        this.line = line;
        this.col = col;
    }

    public static SQLToken of(TokenKind kind, int line, int col) {
        return new SQLToken(kind, line, col);
    }


    @Override
    public String toString() {
        return "token " + kind +
                ", line " + line +
                ", col " + col;
    }

    /**
     * https://ronsavage.github.io/SQL/sql-2003-2.bnf.html
     */
    public enum TokenKind {

        EOI,
        EOF,
        ERROR,

        UNQUOTED_IDENTIFIER,
        REVERSE_QUOTED_IDENTIFIER,
        DOUBLE_QUOTED_IDENTIFIER,

        INTEGER_LITERAL,
        DECIMAL_LITERAL,
        FLOATING_POINT_LITERAL,
        BINARY_FLOAT_LITERAL,
        BINARY_DOUBLE_LITERAL,
        STRING_LITERAL,
        N_STRING_LITERAL,

        BIT_VALUE_LITERAL,
        HEXA_DECIMAL_LITERAL,

        Q_STRING_LITERAL,
        NQ_STRING_LITERAL,

        // A
        ACCESS(SQLKeyWord.ACCESS),
        ACCESSIBLE(SQLKeyWord.ACCESSIBLE),
        ACTION(SQLKeyWord.ACTION),
        ADD(SQLKeyWord.ADD),
        ADVANCED(SQLKeyWord.ADVANCED),
        AFTER(SQLKeyWord.AFTER),
        AGENT(SQLKeyWord.AGENT),
        AGGREGATE(SQLKeyWord.AGGREGATE),
        ALGORITHM(SQLKeyWord.ALGORITHM),
        ALL(SQLKeyWord.ALL),
        ALLOCATE(SQLKeyWord.ALLOCATE),
        ALLOW(SQLKeyWord.ALLOW),
        ALTER(SQLKeyWord.ALTER),
        ALWAYS(SQLKeyWord.ALWAYS),
        ANALYZE(SQLKeyWord.ANALYZE),
        AND(SQLKeyWord.AND),
        ANY(),
        ANYDATA(SQLKeyWord.ANYDATA),
        ANYDATASET(SQLKeyWord.ANYDATASET),
        ANYSCHEMA(SQLKeyWord.ANYSCHEMA),
        ANYTYPE(SQLKeyWord.ANYTYPE),
        ARCHIVE(SQLKeyWord.ARCHIVE),
        ARCHIVELOG(SQLKeyWord.ARCHIVELOG),
        ARE(),
        ARRAY(SQLKeyWord.ARRAY),
        APPLY(SQLKeyWord.APPLY),
        AS(SQLKeyWord.AS),
        ASC(SQLKeyWord.ASC),
        ASENSITIVE(),
        ASSOCIATE(SQLKeyWord.ASSOCIATE),
        ASYMMETRIC(),
        AT(SQLKeyWord.AT),
        ATOMIC(),
        ATTRIBUTE(SQLKeyWord.ATTRIBUTE),
        ATTRIBUTES(SQLKeyWord.ATTRIBUTES),
        AUDIT(SQLKeyWord.AUDIT),
        AUTHENTICATED(SQLKeyWord.AUTHENTICATED),
        AUTHID(SQLKeyWord.AUTHID),
        AUTHORIZATION(),
        AUTO(SQLKeyWord.AUTO),
        AUTOALLOCATE(SQLKeyWord.AUTOALLOCATE),
        AUTOEXTEND(SQLKeyWord.AUTOEXTEND),
        AUTONOMOUS_TRANSACTION(SQLKeyWord.AUTONOMOUS_TRANSACTION),
        AVAILABILITY(SQLKeyWord.AVAILABILITY),


        // B
        BASIC(SQLKeyWord.BASIC),
        BASICFILE(SQLKeyWord.BASICFILE),
        BEFORE(SQLKeyWord.BEFORE),
        BEGIN(SQLKeyWord.BEGIN),
        BETWEEN(SQLKeyWord.BETWEEN),
        BFILE(SQLKeyWord.BFILE),
        BIGFILE(SQLKeyWord.BIGFILE),
        BIGINT(SQLKeyWord.BIGINT),
        BINARY(SQLKeyWord.BINARY),
        BINARY_DOUBLE(SQLKeyWord.BINARY_DOUBLE),
        BINARY_FLOAT(SQLKeyWord.BINARY_FLOAT),
        BINARY_INTEGER(SQLKeyWord.BINARY_INTEGER),
        BIT(SQLKeyWord.BIT),
        BLOB(SQLKeyWord.BLOB),
        BLOCK(SQLKeyWord.BLOCK),
        BLOCKSIZE(SQLKeyWord.BLOCKSIZE),
        BODY(SQLKeyWord.BODY),
        BOOL(SQLKeyWord.BOOL),
        BOOLEAN(SQLKeyWord.BOOLEAN),
        BOTH(SQLKeyWord.BOTH),
        BUFFER_POOL(SQLKeyWord.BUFFER_POOL),
        BULK(SQLKeyWord.BULK),
        BY(SQLKeyWord.BY),
        BYTE(SQLKeyWord.BYTE),

        // C
        C(SQLKeyWord.C),
        CACHE(SQLKeyWord.CACHE),
        CALL(SQLKeyWord.CALL),
        CALLED(),
        CAPACITY(SQLKeyWord.CAPACITY),
        CASCADE(SQLKeyWord.CASCADE),
        CASCADED(SQLKeyWord.CASCADED),
        CASE(SQLKeyWord.CASE),
        CAST(),
        CHANGE(SQLKeyWord.CHANGE),
        CHAR(SQLKeyWord.CHAR),
        CHARACTER(SQLKeyWord.CHARACTER),
        CHARSETID(SQLKeyWord.CHARSETID),
        CHARSETFORM(SQLKeyWord.CHARSETFORM),
        CHECK(SQLKeyWord.CHECK),
        CHECKPOINT(SQLKeyWord.CHECKPOINT),
        CHUNK(SQLKeyWord.CHUNK),
        CLEANUP(SQLKeyWord.CLEANUP),
        CLOB(SQLKeyWord.CLOB),
        CLONE(SQLKeyWord.CLONE),
        CLOSE(SQLKeyWord.CLOSE),
        CLUSTER(SQLKeyWord.CLUSTER),
        COALESCE(SQLKeyWord.COALESCE),
        COLLATE(SQLKeyWord.COLLATE),
        COLLECT(SQLKeyWord.COLLECT),
        COL_NEW(SQLKeyWord.COL_NEW),
        COL_OLD(SQLKeyWord.COL_OLD),
        COL_PARENT(SQLKeyWord.COL_PARENT),
        COLUMN(SQLKeyWord.COLUMN),
        COLUMNS(SQLKeyWord.COLUMNS),
        COMMENT(SQLKeyWord.COMMENT),
        COMMIT(SQLKeyWord.COMMIT),
        COMPILE(SQLKeyWord.COMPILE),
        COMPOUND(SQLKeyWord.COMPOUND),
        COMPRESS(SQLKeyWord.COMPRESS),
        CONCURRENTLY(SQLKeyWord.CONCURRENTLY),
        CONNECT(SQLKeyWord.CONNECT),
        CONNECT_BY_ROOT(SQLKeyWord.CONNECT_BY_ROOT),
        CONSISTENT(SQLKeyWord.CONSISTENT),
        CONSTANT(SQLKeyWord.CONSTANT),
        CONSTRAINT(SQLKeyWord.CONSTRAINT),
        CONSTRAINTS(SQLKeyWord.CONSTRAINTS),
        CONSTRUCTOR(SQLKeyWord.CONSTRUCTOR),
        CONTAINER(SQLKeyWord.CONTAINER),
        CONTAINER_MAP(SQLKeyWord.CONTAINER_MAP),
        CONTAINERS_DEFAULT(SQLKeyWord.CONTAINERS_DEFAULT),
        CONTEXT(SQLKeyWord.CONTEXT),
        CONTINUE(SQLKeyWord.CONTINUE),
        CONTROLFILE(SQLKeyWord.CONTROLFILE),
        CONVERT(SQLKeyWord.CONVERT),
        CORRESPONDING(),
        COUNT(SQLKeyWord.COUNT),
        COVERAGE(SQLKeyWord.COVERAGE),
        CREATE(SQLKeyWord.CREATE),
        CREATION(SQLKeyWord.CREATION),
        CROSS(SQLKeyWord.CROSS),
        CUBE(SQLKeyWord.CUBE),
        CURRENT(SQLKeyWord.CURRENT),
        CURRENT_DATE(SQLKeyWord.CURRENT_DATE),
        CURRENT_DEFAULT_TRANSFORM_GROUP(),
        CURRENT_PATH(),
        CURRENT_ROLE(),
        CURRENT_TIME(SQLKeyWord.CURRENT_TIME),
        CURRENT_TIMESTAMP(),
        CURRENT_TRANSFORM_GROUP_FOR_TYPE(),
        CURRENT_USER(SQLKeyWord.CURRENT_USER),
        CURRVAL(SQLKeyWord.CURRVAL),
        CURSOR(SQLKeyWord.CURSOR),
        CYCLE(SQLKeyWord.CYCLE),


        // D
        DATA(SQLKeyWord.DATA),
        DATABASE(SQLKeyWord.DATABASE),
        DATAFILE(SQLKeyWord.DATAFILE),
        DATAFILES(SQLKeyWord.DATAFILES),
        DATE(SQLKeyWord.DATE),
        DATETIME(SQLKeyWord.DATETIME),
        DAY(SQLKeyWord.DAY),
        DAY_MICROSECOND(SQLKeyWord.DAY_MICROSECOND),
        DAY_MINUTE(SQLKeyWord.DAY_MINUTE),
        DAY_SECOND(SQLKeyWord.DAY_SECOND),
        DB_ROLE_CHANGE(SQLKeyWord.DB_ROLE_CHANGE),
        DDL(SQLKeyWord.DDL),
        DEALLOCATE(SQLKeyWord.DEALLOCATE),
        DEBUG(SQLKeyWord.DEBUG),
        DEC(SQLKeyWord.DEC),
        DECIMAL(SQLKeyWord.DECIMAL),
        DECLARE(SQLKeyWord.DECLARE),
        DECRYPT(SQLKeyWord.DECRYPT),
        DEDUPLICATE(SQLKeyWord.DEDUPLICATE),
        DEFAULT(SQLKeyWord.DEFAULT),
        DEFERRABLE(SQLKeyWord.DEFERRABLE),
        DEFERRED(SQLKeyWord.DEFERRED),
        DEFINER(SQLKeyWord.DEFINER),
        DEFINITION(SQLKeyWord.DEFINITION),
        DELAYED(SQLKeyWord.DELAYED),
        DELETE(SQLKeyWord.DELETE),
        DEPRECATE(SQLKeyWord.DEPRECATE),
        DEREF(),

        DESC(SQLKeyWord.DESC),
        DESCRIBE(SQLKeyWord.DESCRIBE),
        DETERMINISTIC(SQLKeyWord.DETERMINISTIC),
        DIRECTORY(SQLKeyWord.DIRECTORY),
        DISABLE(SQLKeyWord.DISABLE),
        DISALLOW(SQLKeyWord.DISALLOW),
        DISASSOCIATE(SQLKeyWord.DISASSOCIATE),
        DISCARD(SQLKeyWord.DISCARD),
        DISCONNECT(SQLKeyWord.DISCONNECT),
        DISTINCT(SQLKeyWord.DISTINCT),
        DISTINCTROW(SQLKeyWord.DISTINCTROW),
        DIV(SQLKeyWord.DIV),
        DML(SQLKeyWord.DML),
        DOUBLE(SQLKeyWord.DOUBLE),
        DROP(SQLKeyWord.DROP),
        DUPLICATE(SQLKeyWord.DUPLICATE),
        DUPLICATED(SQLKeyWord.DUPLICATED),
        DURATION(SQLKeyWord.DURATION),
        DYNAMIC(),

        // E
        E(SQLKeyWord.E),
        EACH(SQLKeyWord.EACH),
        EDITION(SQLKeyWord.EDITION),
        EDITIONABLE(SQLKeyWord.EDITIONABLE),
        EDITIONING(SQLKeyWord.EDITIONING),
        ELEMENT(SQLKeyWord.ELEMENT),
        ELSE(SQLKeyWord.ELSE),
        ELSEIF(SQLKeyWord.ELSEIF),
        ENABLE(SQLKeyWord.ENABLE),
        ENCRYPT(SQLKeyWord.ENCRYPT),
        END(SQLKeyWord.END),
        ENUM(SQLKeyWord.ENUM),
        ERRORS(SQLKeyWord.ERRORS),
        ESCAPE(),
        EXCEPT(SQLKeyWord.EXCEPT),
        EXCEPTION(SQLKeyWord.EXCEPTION),
        EXCEPTION_INIT(SQLKeyWord.EXCEPTION_INIT),
        EXCEPTIONS(SQLKeyWord.EXCEPTIONS),
        EXCHANGE(SQLKeyWord.EXCHANGE),
        EXCLUDING(SQLKeyWord.EXCLUDING),
        EXEC(),
        EXECUTE(SQLKeyWord.EXECUTE),
        EXIT(SQLKeyWord.EXIT),
        EXISTS(SQLKeyWord.EXISTS),
        EXPLAIN(SQLKeyWord.EXPLAIN),
        EXTEND(SQLKeyWord.EXTEND),
        EXTENDED(SQLKeyWord.EXTENDED),
        EXTENT(SQLKeyWord.EXTENT),
        EXTERNAL(SQLKeyWord.EXTERNAL),
        EXTERNALLY(SQLKeyWord.EXTERNALLY),

        // F
        FALSE(SQLKeyWord.FALSE),
        FETCH(SQLKeyWord.FETCH),
        FLASH_CACHE(SQLKeyWord.FLASH_CACHE),
        FILE_NAME_CONVERT(SQLKeyWord.FILE_NAME_CONVERT),
        FILESYSTEM_LIKE_LOGGING(SQLKeyWord.FILESYSTEM_LIKE_LOGGING),
        FILTER(SQLKeyWord.FILTER),
        FINAL(SQLKeyWord.FINAL),
        FIRST(SQLKeyWord.FIRST),
        FLASHBACK(SQLKeyWord.FLASHBACK),
        FLOAT(SQLKeyWord.FLOAT),
        FOLLOWING(SQLKeyWord.FOLLOWING),
        FOLLOWS(SQLKeyWord.FOLLOWS),
        FOR(SQLKeyWord.FOR),
        FORALL(SQLKeyWord.FORALL),
        FORCE(SQLKeyWord.FORCE),
        FOREIGN(SQLKeyWord.FOREIGN),
        FORMAT(SQLKeyWord.FORMAT),
        FREE(SQLKeyWord.FREE),
        FREELIST(SQLKeyWord.FREELIST),
        FREELISTS(SQLKeyWord.FREELISTS),
        FREEPOOLS(SQLKeyWord.FREEPOOLS),
        FROM(SQLKeyWord.FROM),
        FULL(SQLKeyWord.FULL),
        FUNCTION(SQLKeyWord.FUNCTION),

        // G
        G(SQLKeyWord.G),
        GENERATED(SQLKeyWord.GENERATED),
        GET(SQLKeyWord.GET),
        GLOBAL(SQLKeyWord.GLOBAL),
        GLOBALLY(SQLKeyWord.GLOBALLY),
        GOTO(SQLKeyWord.GOTO),
        GRANT(SQLKeyWord.GRANT),
        GROUP(SQLKeyWord.GROUP),
        GROUPING(SQLKeyWord.GROUPING),
        GROUPS(SQLKeyWord.GROUPS),

        // H
        HASH(SQLKeyWord.HASH),
        HAVING(SQLKeyWord.HAVING),
        HEAP(SQLKeyWord.HEAP),
        HIGH(SQLKeyWord.HIGH),
        HIGH_PRIORITY(SQLKeyWord.HIGH_PRIORITY),

        HOLD(),
        HOUR(SQLKeyWord.HOUR),
        HOUR_MICROSECOND(SQLKeyWord.HOUR_MICROSECOND),
        HOUR_MINUTE(SQLKeyWord.HOUR_MINUTE),
        HOUR_SECOND(SQLKeyWord.HOUR_SECOND),

        // I
        ID(SQLKeyWord.ID),
        IDENTIFIED(SQLKeyWord.IDENTIFIED),
        IDENTIFIER(SQLKeyWord.IDENTIFIER),
        IDENTITY(SQLKeyWord.IDENTITY),
        IF(SQLKeyWord.IF),
        IFNULL(SQLKeyWord.IFNULL),
        IGNORE(SQLKeyWord.IGNORE),
        ILM(SQLKeyWord.ILM),
        IMMEDIATE(SQLKeyWord.IMMEDIATE),
        IMPORT(SQLKeyWord.IMPORT),
        IN(SQLKeyWord.IN),
        INCLUDING(SQLKeyWord.INCLUDING),
        INCREMENT(SQLKeyWord.INCREMENT),
        INDEX(SQLKeyWord.INDEX),
        INDEXING(SQLKeyWord.INDEXING),
        INDEXTYPE(SQLKeyWord.INDEXTYPE),
        INDICATOR(),
        INDICES(SQLKeyWord.INDICES),
        INITIAL(SQLKeyWord.INITIAL),
        INITIALLY(SQLKeyWord.INITIALLY),
        INITRANS(SQLKeyWord.INITRANS),
        INLINE(SQLKeyWord.INLINE),
        INMEMORY(SQLKeyWord.INMEMORY),
        INNER(SQLKeyWord.INNER),
        INOUT(SQLKeyWord.INOUT),
        INPUT(),
        INSENSITIVE(),
        INSERT(SQLKeyWord.INSERT),
        INSTANCE(SQLKeyWord.INSTANCE),
        INSTANTIABLE(SQLKeyWord.INSTANTIABLE),
        INSTEAD(SQLKeyWord.INSTEAD),
        INT(SQLKeyWord.INT),
        INTEGER(SQLKeyWord.INTEGER),
        INTERSECT(),
        INTERVAL(SQLKeyWord.INTERVAL),
        INTO(SQLKeyWord.INTO),
        INVALIDATE(SQLKeyWord.INVALIDATE),
        INVALIDATION(SQLKeyWord.INVALIDATION),
        INVISIBLE(SQLKeyWord.INVISIBLE),
        INVOKER(SQLKeyWord.INVOKER),
        IS(SQLKeyWord.IS),
        ISOLATION(),

        // J
        JAVA(SQLKeyWord.JAVA),
        JOIN(SQLKeyWord.JOIN),
        JSON(SQLKeyWord.JSON),

        // K
        K(SQLKeyWord.K),
        KEEP(SQLKeyWord.KEEP),
        KEEP_DUPLICATES(SQLKeyWord.KEEP_DUPLICATES),
        KEY(SQLKeyWord.KEY),
        KEYS(SQLKeyWord.KEYS),

        // L
        LANGUAGE(SQLKeyWord.LANGUAGE),
        LARGE(SQLKeyWord.LARGE),
        LAST(SQLKeyWord.LAST),
        LATERAL(SQLKeyWord.LATERAL),
        LAX(SQLKeyWord.LAX),
        LEADING(),
        LEAF(SQLKeyWord.LEAF),
        LEFT(SQLKeyWord.LEFT),
        LENGTH(SQLKeyWord.LENGTH),
        LESS(SQLKeyWord.LESS),
        LEVEL(SQLKeyWord.LEVEL),
        LEVELS(SQLKeyWord.LEVELS),
        LIBRARY(SQLKeyWord.LIBRARY),
        LIKE(SQLKeyWord.LIKE),
        LIKEC(SQLKeyWord.LIKEC),
        LIKE2(SQLKeyWord.LIKE2),
        LIKE4(SQLKeyWord.LIKE4),
        LIMIT(SQLKeyWord.LIMIT),
        LINK(SQLKeyWord.LINK),
        LIST(SQLKeyWord.LIST),
        LOAD(SQLKeyWord.LOAD),
        LOB(SQLKeyWord.LOB),
        LOBS(SQLKeyWord.LOBS),
        LOCAL(SQLKeyWord.LOCAL),
        LOCALTIME(SQLKeyWord.LOCALTIME),
        LOCALTIMESTAMP(SQLKeyWord.LOCALTIMESTAMP),
        LOCATION(SQLKeyWord.LOCATION),
        LOCATOR(SQLKeyWord.LOCATOR),
        LOCK(SQLKeyWord.LOCK),
        LOCKED(SQLKeyWord.LOCKED),
        LOCKING(SQLKeyWord.LOCKING),
        LOG(SQLKeyWord.LOG),
        LOGFILE(SQLKeyWord.LOGFILE),
        LOGGING(SQLKeyWord.LOGGING),
        LOGOFF(SQLKeyWord.LOGOFF),
        LOGON(SQLKeyWord.LOGON),
        LONG(SQLKeyWord.LONG),
        LONGBLOB(SQLKeyWord.LONGBLOB),
        LONGTEXT(SQLKeyWord.LONGTEXT),
        LOOP(SQLKeyWord.LOOP),
        LOW(SQLKeyWord.LOW),
        LOW_PRIORITY(SQLKeyWord.LOW_PRIORITY),

        // M
        M(SQLKeyWord.M),
        MANAGEMENT(SQLKeyWord.MANAGEMENT),
        MAP(SQLKeyWord.MAP),
        MAPPING(SQLKeyWord.MAPPING),
        MATCH(SQLKeyWord.MATCH),
        MATERIALIZED(SQLKeyWord.MATERIALIZED),
        MAX(SQLKeyWord.MAX),
        MAXEXTENTS(SQLKeyWord.MAXEXTENTS),
        MAXDATAFILES(SQLKeyWord.MAXDATAFILES),
        MAXINSTANCES(SQLKeyWord.MAXINSTANCES),
        MAXLEN(SQLKeyWord.MAXLEN),
        MAXLOGFILES(SQLKeyWord.MAXLOGFILES),
        MAXLOGHISTORY(SQLKeyWord.MAXLOGHISTORY),
        MAXLOGMEMBERS(SQLKeyWord.MAXLOGMEMBERS),
        MAXSIZE(SQLKeyWord.MAXSIZE),
        MAXVALUE(SQLKeyWord.MAXVALUE),
        MEDIUMBLOB(SQLKeyWord.MEDIUMBLOB),
        MEDIUMINT(SQLKeyWord.MEDIUMINT),
        MEDIUMTEXT(SQLKeyWord.MEDIUMTEXT),
        MEMBER(SQLKeyWord.MEMBER),
        MEMCOMPRESS(SQLKeyWord.MEMCOMPRESS),
        MEMOPTIMIZE(SQLKeyWord.MEMOPTIMIZE),

        MERGE(SQLKeyWord.MERGE),
        METADATA(SQLKeyWord.METADATA),
        METHOD(),
        MICROSECOND(SQLKeyWord.MICROSECOND),
        MIN(SQLKeyWord.MIN),
        MINEXTENTS(SQLKeyWord.MINEXTENTS),
        MINING(SQLKeyWord.MINING),
        MINUS(SQLKeyWord.MINUS),

        MINUTE(SQLKeyWord.MINUTE),
        MINUTE_MICROSECOND(SQLKeyWord.MINUTE_MICROSECOND),
        MINUTE_SECOND(SQLKeyWord.MINUTE_SECOND),
        MINVALUE(SQLKeyWord.MINVALUE),
        MOD(SQLKeyWord.MOD),
        MODE(SQLKeyWord.MODE),
        MODIFIES(),
        MODIFY(SQLKeyWord.MODIFY),
        MODULE(),
        MONTH(SQLKeyWord.MONTH),
        MOVEMENT(SQLKeyWord.MOVEMENT),
        MULTISET(),

        // N
        NAME(SQLKeyWord.NAME),
        NATIONAL(SQLKeyWord.NATIONAL),
        NATURAL(SQLKeyWord.NATURAL),
        NCHAR(SQLKeyWord.NCHAR),
        NCLOB(SQLKeyWord.NCLOB),
        NESTED(SQLKeyWord.NESTED),
        NEW(SQLKeyWord.NEW),
        NEXT(SQLKeyWord.NEXT),
        NEXTVAL(SQLKeyWord.NEXTVAL),
        NO(SQLKeyWord.NO),
        NOARCHIVELOG(SQLKeyWord.NOARCHIVELOG),
        NOAUDIT(SQLKeyWord.NOAUDIT),
        NOCACHE(SQLKeyWord.NOCACHE),
        NOCOMPRESS(SQLKeyWord.NOCOMPRESS),
        NOCOPY(SQLKeyWord.NOCOPY),
        NOCYCLE(SQLKeyWord.NOCYCLE),
        NOEXTEND(SQLKeyWord.NOEXTEND),
        NOKEEP(SQLKeyWord.NOKEEP),
        NOLOGGING(SQLKeyWord.NOLOGGING),
        NOMAPPING(SQLKeyWord.NOMAPPING),
        NOMAXVALUE(SQLKeyWord.NOMAXVALUE),
        NOMINVALUE(SQLKeyWord.NOMINVALUE),
        NONE(SQLKeyWord.NONE),
        NONEDITIONABLE(SQLKeyWord.NONEDITIONABLE),
        NONSCHEMA(SQLKeyWord.NONSCHEMA),
        NOORDER(SQLKeyWord.NOORDER),
        NOPARALLEL(SQLKeyWord.NOPARALLEL),
        NORELY(SQLKeyWord.NORELY),
        NOSCALE(SQLKeyWord.NOSCALE),
        NOT(SQLKeyWord.NOT),
        NOVALIDATE(SQLKeyWord.NOVALIDATE),
        NOWAIT(SQLKeyWord.NOWAIT),
        NULL(SQLKeyWord.NULL),
        NULLIF(SQLKeyWord.NULLIF),
        NUMBER(SQLKeyWord.NUMBER),
        NUMERIC(SQLKeyWord.NUMERIC),
        NVARCHAR2(SQLKeyWord.NVARCHAR2),


        // O
        OBJECT(SQLKeyWord.OBJECT),
        OF(SQLKeyWord.OF),
        OFF(SQLKeyWord.OFF),
        OFFSET(SQLKeyWord.OFFSET),
        OJ(SQLKeyWord.OJ),
        OID(SQLKeyWord.OID),
        OIDINDEX(SQLKeyWord.OIDINDEX),
        OLD(SQLKeyWord.OLD),
        ON(SQLKeyWord.ON),
        ONLINE(SQLKeyWord.ONLINE),
        ONLY(SQLKeyWord.ONLY),
        OPAQUE(SQLKeyWord.OPAQUE),
        OPEN(SQLKeyWord.OPEN),
        OPERATOR(SQLKeyWord.OPERATOR),
        OPTIMAL(SQLKeyWord.OPTIMAL),
        OPTIMIZE(SQLKeyWord.OPTIMIZE),
        OPTION(SQLKeyWord.OPTION),
        OR(SQLKeyWord.OR),
        ORDER(SQLKeyWord.ORDER),
        ORGANIZATION(SQLKeyWord.ORGANIZATION),
        OUT(SQLKeyWord.OUT),
        OUTER(SQLKeyWord.OUTER),
        OUTPUT(SQLKeyWord.OUTPUT),
        OVER(SQLKeyWord.OVER),
        OVERFLOW(SQLKeyWord.OVERFLOW),
        OVERLAPS(SQLKeyWord.OVERLAPS),
        OVERRIDING(SQLKeyWord.OVERRIDING),

        // P
        P(SQLKeyWord.P),
        PACKAGE(SQLKeyWord.PACKAGE),
        PARAMETER(SQLKeyWord.PARAMETER),
        PARAMETERS(SQLKeyWord.PARAMETERS),
        PARALLEL(SQLKeyWord.PARALLEL),
        PARALLEL_ENABLE(SQLKeyWord.PARALLEL_ENABLE),
        PARENT(SQLKeyWord.PARENT),
        PARTIAL(SQLKeyWord.PARTIAL),
        PARTITION(SQLKeyWord.PARTITION),
        PARTITIONING(SQLKeyWord.PARTITIONING),
        PARTITIONS(SQLKeyWord.PARTITIONS),
        PCTINCREASE(SQLKeyWord.PCTINCREASE),
        PCTFREE(SQLKeyWord.PCTFREE),
        PCTTHRESHOLD(SQLKeyWord.PCTTHRESHOLD),
        PCTUSED(SQLKeyWord.PCTUSED),
        PCTVERSION(SQLKeyWord.PCTVERSION),
        PERFORMANCE(SQLKeyWord.PERFORMANCE),
        PERIOD(SQLKeyWord.PERIOD),
        PIPE(SQLKeyWord.PIPE),
        PIPELINED(SQLKeyWord.PIPELINED),
        PLS_INTEGER(SQLKeyWord.PLS_INTEGER),
        POLICY(SQLKeyWord.POLICY),
        PRAGMA(SQLKeyWord.PRAGMA),
        PRECEDING(SQLKeyWord.PRECEDING),
        PRECEDES(SQLKeyWord.PRECEDES),
        PRECISION(SQLKeyWord.PRECISION),
        PREPARE(SQLKeyWord.PREPARE),
        PRESERVE(SQLKeyWord.PRESERVE),
        PRIMARY(SQLKeyWord.PRIMARY),
        PRIVATE(SQLKeyWord.PRIVATE),
        PRIOR(SQLKeyWord.PRIOR),
        PROCEDURE(SQLKeyWord.PROCEDURE),
        PUBLIC(SQLKeyWord.PUBLIC),
        PURGE(SQLKeyWord.PURGE),
        PLUGGABLE(SQLKeyWord.PLUGGABLE),

        // Q
        QUARTER(SQLKeyWord.QUARTER),
        QUERY(SQLKeyWord.QUERY),
        QUICK(SQLKeyWord.QUICK),

        // R
        RAISE(SQLKeyWord.RAISE),
        RANGE(SQLKeyWord.RANGE),
        RAW(SQLKeyWord.RAW),
        READ(SQLKeyWord.READ),
        READS(SQLKeyWord.READS),
        REAL(SQLKeyWord.REAL),
        REBUILD(SQLKeyWord.REBUILD),
        RECORD(SQLKeyWord.RECORD),
        RECURSIVE(SQLKeyWord.RECURSIVE),
        RECYCLE(SQLKeyWord.RECYCLE),
        REF(SQLKeyWord.REF),
        REFERENCE(SQLKeyWord.REFERENCE),
        REFERENCES(SQLKeyWord.REFERENCES),
        REFERENCING(SQLKeyWord.REFERENCING),
        REGEXP(SQLKeyWord.REGEXP),
        REJECT(SQLKeyWord.REJECT),
        RELATIONAL(SQLKeyWord.RELATIONAL),
        RELY(SQLKeyWord.RELY),
        REMOVE(SQLKeyWord.REMOVE),
        REPLACE(SQLKeyWord.REPLACE),
        REGR_AVGX(),
        REGR_AVGY(),
        REGR_COUNT(),
        REGR_INTERCEPT(),
        REGR_R2(),
        REGR_SLOPE(),
        REGR_SXX(),
        REGR_SXY(),
        REGR_SYY(),
        RELEASE(SQLKeyWord.RELEASE),
        RELIES_ON(SQLKeyWord.RELIES_ON),
        RENAME(SQLKeyWord.RENAME),
        REORGANIZE(SQLKeyWord.REORGANIZE),
        REPAIR(SQLKeyWord.REPAIR),
        REPEAT(SQLKeyWord.REPEAT),
        RESET(SQLKeyWord.RESET),
        RESTRICT(SQLKeyWord.RESTRICT),
        RESTRICT_REFERENCES(SQLKeyWord.RESTRICT_REFERENCES),
        RESULT(SQLKeyWord.RESULT),
        RESULT_CACHE(SQLKeyWord.RESULT_CACHE),
        RETENTION(SQLKeyWord.RETENTION),
        RETURN(SQLKeyWord.RETURN),
        RETURNING(SQLKeyWord.RETURNING),
        RETURNS(SQLKeyWord.RETURNS),
        REUSE(SQLKeyWord.REUSE),
        REVERSE(SQLKeyWord.REVERSE),
        REVOKE(SQLKeyWord.REVOKE),
        RIGHT(SQLKeyWord.RIGHT),
        RLIKE(SQLKeyWord.RLIKE),
        ROLE(SQLKeyWord.ROLE),
        ROLLBACK(SQLKeyWord.ROLLBACK),
        ROLLUP(SQLKeyWord.ROLLUP),
        ROW(SQLKeyWord.ROW),
        ROWID(SQLKeyWord.ROWID),
        ROWNUM(SQLKeyWord.ROWNUM),
        ROWS(SQLKeyWord.ROWS),
        ROWTYPE(SQLKeyWord.ROWTYPE),

        // S
        SAVE(SQLKeyWord.SAVE),
        SAVEPOINT(SQLKeyWord.SAVEPOINT),
        SCALE(SQLKeyWord.SCALE),
        SCHEMA(SQLKeyWord.SCHEMA),
        SCOPE(SQLKeyWord.SCOPE),
        SCROLL(SQLKeyWord.SCROLL),
        SEARCH(SQLKeyWord.SEARCH),
        SECOND(SQLKeyWord.SECOND),
        SECOND_MICROSECOND(SQLKeyWord.SECOND_MICROSECOND),
        SECUREFILE(SQLKeyWord.SECUREFILE),
        SECURITY(SQLKeyWord.SECURITY),
        SEED(SQLKeyWord.SEED),
        SEGMENT(SQLKeyWord.SEGMENT),
        SELECT(SQLKeyWord.SELECT),
        SELF(SQLKeyWord.SELF),
        SENSITIVE(SQLKeyWord.SENSITIVE),
        SEQUENCE(SQLKeyWord.SEQUENCE),
        SERIALLY_REUSABLE(SQLKeyWord.SERIALLY_REUSABLE),
        SERVERERROR(SQLKeyWord.SERVERERROR),
        SESSION(SQLKeyWord.SESSION),
        SESSION_USER(SQLKeyWord.SESSION_USER),
        SET(SQLKeyWord.SET),
        SETTINGS(SQLKeyWord.SETTINGS),
        SHARE(SQLKeyWord.SHARE),
        SHARED(SQLKeyWord.SHARED),
        SHARING(SQLKeyWord.SHARING),
        SHUTDOWN(SQLKeyWord.SHUTDOWN),
        SIMILAR(SQLKeyWord.SIMILAR),
        SIMPLE(SQLKeyWord.SIMPLE),
        SIZE(SQLKeyWord.SIZE),
        SKIP(SQLKeyWord.SKIP),
        SMALLFILE(SQLKeyWord.SMALLFILE),
        SMALLINT(SQLKeyWord.SMALLINT),
        SOME(SQLKeyWord.SOME),
        SORT(SQLKeyWord.SORT),
        SOUNDS(SQLKeyWord.SOUNDS),
        SPECIFIC(SQLKeyWord.SPECIFIC),
        SPECIFICATION(SQLKeyWord.SPECIFICATION),
        SPECIFICTYPE(SQLKeyWord.SPECIFICTYPE),
        SPLIT(SQLKeyWord.SPLIT),
        SQL(SQLKeyWord.SQL),
        SQL_BIG_RESULT(SQLKeyWord.SQL_BIG_RESULT),
        SQL_CACHE(SQLKeyWord.SQL_CACHE),
        SQL_CALC_FOUND_ROWS(SQLKeyWord.SQL_CALC_FOUND_ROWS),
        SQL_BUFFER_RESULT(SQLKeyWord.SQL_BUFFER_RESULT),
        SQL_NO_CACHE(SQLKeyWord.SQL_NO_CACHE),
        SQL_SMALL_RESULT(SQLKeyWord.SQL_SMALL_RESULT),
        SQLEXCEPTION(SQLKeyWord.SQLEXCEPTION),
        SQLSTATE(SQLKeyWord.SQLSTATE),
        SQLWARNING(SQLKeyWord.SQLWARNING),
        STANDBY(SQLKeyWord.STANDBY),
        START(SQLKeyWord.START),
        STARTUP(SQLKeyWord.STARTUP),
        STATEMENT(SQLKeyWord.STATEMENT),
        STATIC(SQLKeyWord.STATIC),
        STATISTICS(SQLKeyWord.STATISTICS),
        STORE(SQLKeyWord.STORE),
        STORAGE(SQLKeyWord.STORAGE),
        STRAIGHT_JOIN(SQLKeyWord.STRAIGHT_JOIN),
        STRICT(SQLKeyWord.STRICT),
        STRING(SQLKeyWord.STRING),
        STRUCT(SQLKeyWord.STRUCT),
        SYSAUX(SQLKeyWord.SYSAUX),
        SUBMULTISET(SQLKeyWord.SUBMULTISET),
        SUBPARTITION(SQLKeyWord.SUBPARTITION),
        SUBTYPE(SQLKeyWord.SUBTYPE),
        SUBPARTITIONS(SQLKeyWord.SUBPARTITIONS),
        SUBSTITUTABLE(SQLKeyWord.SUBSTITUTABLE),
        SUPPLEMENT(SQLKeyWord.SUPPLEMENT),
        SUSPEND(SQLKeyWord.SUSPEND),
        SYMMETRIC(SQLKeyWord.SYMMETRIC),
        SYNONYM(SQLKeyWord.SYNONYM),
        SYS(SQLKeyWord.SYS),
        SYSTEM(SQLKeyWord.SYSTEM),
        SYSTEM_USER(SQLKeyWord.SYSTEM_USER),

        // T
        T(SQLKeyWord.T),
        TABLE(SQLKeyWord.TABLE),
        TABLES(SQLKeyWord.TABLES),
        TABLESPACE(SQLKeyWord.TABLESPACE),
        TDO(SQLKeyWord.TDO),
        TEMPFILE(SQLKeyWord.TEMPFILE),
        TEMPORARY(SQLKeyWord.TEMPORARY),
        TEMPLATE(SQLKeyWord.TEMPLATE),
        TEXT(SQLKeyWord.TEXT),
        THAN(SQLKeyWord.THAN),
        THEN(SQLKeyWord.THEN),
        TIME(SQLKeyWord.TIME),
        TIME_ZONE(SQLKeyWord.TIME_ZONE),
        TIMESTAMP(SQLKeyWord.TIMESTAMP),

        TIMEZONE_ABBR(SQLKeyWord.TIMEZONE_ABBR),
        TIMEZONE_HOUR(SQLKeyWord.TIMEZONE_HOUR),
        TIMEZONE_MINUTE(SQLKeyWord.TIMEZONE_MINUTE),
        TIMEZONE_REGION(SQLKeyWord.TIMEZONE_REGION),
        TINYBLOB(SQLKeyWord.TINYBLOB),
        TINYINT(SQLKeyWord.TINYINT),
        TINYTEXT(SQLKeyWord.TINYTEXT),
        TO(SQLKeyWord.TO),
        TRAILING(SQLKeyWord.TRAILING),
        TRANSLATION(SQLKeyWord.TRANSLATION),
        TREAT(SQLKeyWord.TREAT),
        TRIGGER(SQLKeyWord.TRIGGER),
        TRIGGERS(SQLKeyWord.TRIGGERS),
        TRIM(SQLKeyWord.TRIM),
        TRUE(SQLKeyWord.TRUE),
        TRUNCATE(SQLKeyWord.TRUNCATE),
        TYPE(SQLKeyWord.TYPE),

        // U
        UDF(SQLKeyWord.UDF),
        UESCAPE(SQLKeyWord.UESCAPE),
        UNDER(SQLKeyWord.UNDER),
        UNDO(SQLKeyWord.UNDO),
        UNIFORM(SQLKeyWord.UNIFORM),
        UNION(SQLKeyWord.UNION),
        UNIQUE(SQLKeyWord.UNIQUE),
        UNKNOWN(SQLKeyWord.UNKNOWN),
        UNLIMITED(SQLKeyWord.UNLIMITED),
        UNNEST(SQLKeyWord.UNNEST),
        UNPACKAGE(SQLKeyWord.UNPACKAGE),
        UNPLUG(SQLKeyWord.UNPLUG),
        UNUSABLE(SQLKeyWord.UNUSABLE),
        UNUSED(SQLKeyWord.UNUSED),
        UNSIGNED(SQLKeyWord.UNSIGNED),
        UPDATE(SQLKeyWord.UPDATE),
        UPGRADE(SQLKeyWord.UPGRADE),
        UPPER(SQLKeyWord.UPPER),

        URITYPE(SQLKeyWord.URITYPE),
        UROWID(SQLKeyWord.UROWID),
        USER(SQLKeyWord.USER),
        USER_DATA(SQLKeyWord.USER_DATA),
        USING(SQLKeyWord.USING),

        // V
        VALIDATE(SQLKeyWord.VALIDATE),
        VALUE(SQLKeyWord.VALUE),
        VALUES(SQLKeyWord.VALUES),
        VAR_POP(),
        VAR_SAMP(),
        VARBINARY(SQLKeyWord.VARBINARY),
        VARCHAR(SQLKeyWord.VARCHAR),
        VARCHAR2(SQLKeyWord.VARCHAR2),
        VARRAY(SQLKeyWord.VARRAY),
        VARRAYS(SQLKeyWord.VARRAYS),
        VARYING(SQLKeyWord.VARYING),
        VIEW(SQLKeyWord.VIEW),
        VIRTUAL(SQLKeyWord.VIRTUAL),
        VISIBLE(SQLKeyWord.VISIBLE),

        // W
        WAIT(SQLKeyWord.WAIT),
        WEEK(SQLKeyWord.WEEK),
        WHEN(SQLKeyWord.WHEN),
        WHENEVER(SQLKeyWord.WHENEVER),
        WHERE(SQLKeyWord.WHERE),
        WHILE(SQLKeyWord.WHILE),
        WIDTH_BUCKET(SQLKeyWord.WIDTH_BUCKET),
        WINDOW(SQLKeyWord.WINDOW),
        WITH(SQLKeyWord.WITH),
        WITHIN(SQLKeyWord.WITHIN),
        WITHOUT(SQLKeyWord.WITHOUT),
        WRITE(SQLKeyWord.WRITE),

        // X
        XML(SQLKeyWord.XML),
        XMLSCHEMA(SQLKeyWord.XMLSCHEMA),
        XMLTYPE(SQLKeyWord.XMLTYPE),
        XOR(SQLKeyWord.XOR),

        // Y
        YEAR(SQLKeyWord.YEAR),
        YEAR_MONTH(SQLKeyWord.YEAR_MONTH),

        // Z
        ZEROFILL(SQLKeyWord.ZEROFILL),
        ZONE(SQLKeyWord.ZONE),
        ZONEMAP(SQLKeyWord.ZONEMAP),

        ARROW(SQLKeyWord.ARROW),
        ASSIGN(SQLKeyWord.ASSIGN),
        COLCOL(SQLKeyWord.COLCOL),
        LPAREN(SQLKeyWord.LPAREN),
        RPAREN(SQLKeyWord.RPAREN),
        LBRACE(SQLKeyWord.LBRACE),
        RBRACE(SQLKeyWord.RBRACE),
        LBRACKET(SQLKeyWord.LBRACKET),
        RBRACKET(SQLKeyWord.RBRACKET),
        SEMI(SQLKeyWord.SEMI),
        COMMA(SQLKeyWord.COMMA),
        DOT(SQLKeyWord.DOT),
        DOTDOT(SQLKeyWord.DOTDOT),
        ELLIPSIS(SQLKeyWord.ELLIPSIS),
        EQ(SQLKeyWord.EQ),
        GT(SQLKeyWord.GT),
        LT(SQLKeyWord.LT),
        BANG(SQLKeyWord.BANG),
        TILDE(SQLKeyWord.TILDE),
        QUES(SQLKeyWord.QUES),
        COLON(SQLKeyWord.COLON),
        EQEQ(SQLKeyWord.EQEQ),
        LTEQ(SQLKeyWord.LTEQ),
        GTEQ(SQLKeyWord.GTEQ),
        BANGEQ(SQLKeyWord.BANGEQ),
        LTGT(SQLKeyWord.LTGT),
        EQGT(SQLKeyWord.EQGT),
        LTEQGT(SQLKeyWord.LTEQGT),
        AMPAMP(SQLKeyWord.AMPAMP),
        BARBAR(SQLKeyWord.BARBAR),
        PLUSPLUS(SQLKeyWord.PLUSPLUS),
        SUBSUB(SQLKeyWord.SUBSUB),
        PLUS(SQLKeyWord.PLUS),
        SUB(SQLKeyWord.SUB),
        STAR(SQLKeyWord.STAR),
        SLASH(SQLKeyWord.SLASH),
        AMP(SQLKeyWord.AMP),
        BAR(SQLKeyWord.BAR),
        CARET(SQLKeyWord.CARET),
        PERCENT(SQLKeyWord.PERCENT),
        LTLT(SQLKeyWord.LTLT),
        GTGT(SQLKeyWord.GTGT),
        GTGTGT(SQLKeyWord.GTGTGT),
        PLUSEQ(SQLKeyWord.PLUSEQ),
        SUBEQ(SQLKeyWord.SUBEQ),
        STAREQ(SQLKeyWord.STAREQ),
        SLASHEQ(SQLKeyWord.SLASHEQ),
        AMPEQ(SQLKeyWord.AMPEQ),
        BAREQ(SQLKeyWord.BAREQ),
        CARETEQ(SQLKeyWord.CARETEQ),
        PERCENTEQ(SQLKeyWord.PERCENTEQ),
        LTLTEQ(SQLKeyWord.LTLTEQ),
        GTGTEQ(SQLKeyWord.GTGTEQ),
        GTGTGTEQ(SQLKeyWord.GTGTGT),
        MONKEYS_AT(SQLKeyWord.MONKEYS_AT),
        SHARP(SQLKeyWord.SHARP),
        ;

        public final SQLKeyWord keyWord;

        TokenKind() {
            this(null);
        }

        TokenKind(SQLKeyWord keyWord) {
            this.keyWord = keyWord;
        }


    }


}
